"use client";

import { useState } from "react";

const visualOverrides = `
  .draft-home{--ink:#141822;--paper:#eef0ea;--signal:#c8f450;background-color:#171d29;background-image:linear-gradient(#ffffff08 1px,transparent 1px),linear-gradient(90deg,#ffffff08 1px,transparent 1px),radial-gradient(circle at 68% 12%,#5e2cb91f,transparent 25%),radial-gradient(circle at 15% 72%,#08a9c81a,transparent 29%);background-size:64px 64px,64px 64px,auto,auto}
  .draft-section,.draft-index,.draft-nav{border-color:#ffffff1c}.draft-card{background:#1b2230;border:1px solid #ffffff14}.draft-card:nth-child(2){background:#17292d}.draft-card:nth-child(3){background:#28233a}.draft-closing{background:#141822;border-top:1px solid #ffffff1c}
  .portal-menu-toggle{left:22px;right:auto;width:42px;height:36px;border:0;background:transparent;padding:0;justify-items:center}.portal-menu-toggle span{width:23px;height:4px;border-radius:999px}.portal-menu{border-left:0;border-right:1px solid #ffffff24;inset:0 auto 0 0;transform:translateX(-100%)}.portal-menu.is-open{transform:none}@media(max-width:760px){.portal-menu-toggle{left:14px;right:auto}}
  .portal-ring{inset:13% 21%;border-radius:0;transform:perspective(720px) rotateY(-15deg) rotateZ(3deg);box-shadow:0 0 34px #55d4df55,inset 0 0 52px #070b13}.portal-ring::after{inset:13%;border-radius:0;transform:none;border-color:#c8f450;box-shadow:inset 0 0 28px #c8f45022}.impossible-form{inset:29% 30%;clip-path:polygon(50% 0,100% 100%,0 100%);background:radial-gradient(circle at 50% 72%,#b5f152 0 2%,#2c8a98 4%,#111c29 32%,#07090c 75%);transform:none;filter:drop-shadow(0 20px 24px #0009)}
  .draft-card::after{width:78%;aspect-ratio:1.3;border-radius:0;right:-16%;top:13%;transform:perspective(500px) rotateY(-22deg) rotateZ(4deg);background:linear-gradient(135deg,#6e55d855,transparent 55%);clip-path:polygon(12% 0,100% 0,88% 100%,0 100%)}.draft-card:nth-child(2)::after{transform:perspective(500px) rotateY(20deg) rotateZ(-5deg);clip-path:polygon(0 12%,88% 0,100% 88%,12% 100%)}.draft-card:nth-child(3)::after{border-radius:0;transform:perspective(500px) rotateY(-22deg);clip-path:polygon(50% 0,100% 100%,0 100%)}
  .portal-menu summary{font-size:clamp(38px,7vw,72px);letter-spacing:-.075em;border-bottom:1px solid #ffffff24;padding:12px 0;display:flex;justify-content:space-between;cursor:pointer;list-style:none}.portal-menu summary::-webkit-details-marker{display:none}.portal-submenu{display:grid;padding:8px 0 18px}.portal-submenu a{font:13px 'DM Mono',monospace!important;letter-spacing:.03em!important;border:0!important;padding:9px 0!important;color:#c7cdc2}
`;

export function PortalMenu() {
  const [open, setOpen] = useState(false);
  return <><style>{visualOverrides}</style><button className="portal-menu-toggle" aria-label="Menü öffnen" aria-expanded={open} onClick={() => setOpen(!open)}><span /><span /><span /></button><aside className={`portal-menu ${open ? "is-open" : ""}`} aria-hidden={!open}><div className="portal-menu-top"><span>01 — NAVIGATION</span><button onClick={() => setOpen(false)}>Schließen ×</button></div><nav><a href="/studio">Über uns <i>01</i></a><a href="/kontakt">Kontakt <i>02</i></a><a href="/projekte">Works <i>03</i></a><details><summary>Leistungen <i>04 +</i></summary><div className="portal-submenu"><a href="/leistungen/videoproduktion">Film &amp; Motion Design</a><a href="/leistungen/digital-signage-content">Media Spaces</a><a href="/leistungen/wandmalerei-wanddesign">Wall Design &amp; Malerei</a><a href="/leistungen/logo-design-agentur">Logo &amp; Identity Design</a></div></details><a href="/impressum">Impressum <i>05</i></a></nav><p>Film · Raum · Wand · Identität<br />Gestaltet für Perspektivwechsel.</p></aside></>;
}
