export type Project = { slug:string; number:string; title:string; category:string; subtitle:string; overview:string; challenge:string; approach:string; services:string[]; tone:string };

export const projects: Project[] = [
  {slug:"aurelis",number:"01",title:"Aurelis",category:"Film & Motion Design",subtitle:"Markenfilm für urbane Energie.",overview:"Ein atmosphärischer Markenfilm, der Energie als pulsierenden Teil des Stadtraums erzählt - zwischen Architektur, Bewegung und menschlicher Nähe.",challenge:"Energie sollte nicht als abstrakte Kennzahl erscheinen, sondern als spürbare Kraft im Alltag einer Stadt.",approach:"Nachtblaue Stadträume, goldene Lichtspuren und ruhige Kamerafahrten übersetzen Infrastruktur in Atmosphäre.",services:["Creative Direction","Konzept","Videoproduktion","Motion Design","Sound Design","Color Grading"],tone:"aurelis"},
  {slug:"kantenraum",number:"02",title:"Kantenraum",category:"Wall Design / Anamorphose",subtitle:"Ein Portal für ein Kreativquartier.",overview:"Ein großformatiges Wandbild verbindet zwei Gebäudeseiten zu einem räumlichen Portal, das sich erst aus dem richtigen Blickwinkel vollständig erschließt.",challenge:"Zwei getrennte Flächen sollten zu einer gemeinsamen Landmarke werden, ohne ihre architektonische Eigenständigkeit zu verlieren.",approach:"Beton, tiefes Schwarz, Signalrot und gebrochenes Weiß treffen auf präzise Geometrie. Die Illusion entsteht im Blick der Besucher:innen.",services:["Künstlerisches Konzept","Entwurf","Anamorphe Planung","Wandmalerei","Dokumentation"],tone:"kantenraum"},
  {slug:"voltage-form",number:"03",title:"Voltage / Form",category:"3D & CGI",subtitle:"Licht als modulares Objekt.",overview:"Eine digitale Kampagnenwelt für eine modulare Lichtskulptur, in der technische Präzision und organische Lichtbewegung zusammenkommen.",challenge:"Ein erklärungsbedürftiges Lichtobjekt brauchte eine Bildwelt, die seine Modularität unmittelbar begehrlich macht.",approach:"Chrom, Rauchglas, dunkler Raum und harte Reflexionen bilden einen kontrollierten Kontrast zu leuchtenden Linien.",services:["3D-Visualisierung","CGI","Art Direction","Produktanimation","Still-Renderings"],tone:"voltage"},
  {slug:"nova-district",number:"04",title:"Nova District",category:"Media Spaces",subtitle:"Eine Fläche, die auf Menschen reagiert.",overview:"Ein begehbares Raumerlebnis für eine urbane Kulturmarke. Projektionen, Licht und Sound reagieren auf Bewegungen der Besucher:innen.",challenge:"Aus einer anonymen Markenfläche sollte ein Ort entstehen, der Neugier auslöst und in Erinnerung bleibt.",approach:"Monolithische Raumkörper, projektierte Typografie und Blau-Violett-Licht schaffen eine Umgebung, die sich mit jedem Schritt verändert.",services:["Raumkonzept","Projection Mapping","Digital Signage Content","Lichtdesign","Motion Design","Sound-Konzept"],tone:"nova"},
  {slug:"materia",number:"05",title:"Materia",category:"Logo & Brand Design",subtitle:"Identität für ein Architekturatelier.",overview:"Eine markante Markenidentität für ein Studio an der Schnittstelle von Architektur, Materialforschung und nachhaltigem Bauen.",challenge:"Die Identität sollte fachliche Präzision vermitteln und gleichzeitig Raum für Materialität und Experiment offenlassen.",approach:"Ein reduziertes Wortzeichen, modulare Raster, warme Mineralfarben und geprägte Papiertexturen machen die Marke zu einem haptischen System.",services:["Strategie","Naming-Ansatz","Logo Design","Corporate Design","Typografie","Markenrichtlinien"],tone:"materia"},
  {slug:"shift-human",number:"06",title:"Shift / Human",category:"Recruiting Film",subtitle:"Ein Recruitingfilm über Haltung.",overview:"Ein Recruitingfilm, der nicht Stellen, sondern Haltung zeigt: Menschen, Arbeitsumgebungen und Zukunftsthemen werden direkt inszeniert.",challenge:"Statt austauschbarer Arbeitgeberversprechen sollte ein glaubwürdiges Bild der Kultur entstehen.",approach:"Dokumentarische Nähe, natürliche Hauttöne und präzise Motion Graphics verbinden echte Stimmen mit einer zukunftsgerichteten Bildsprache.",services:["Kampagnenkonzept","Casting-Ansatz","Filmproduktion","Recruiting-Video","Interviewführung","Social Cutdowns"],tone:"shift"},
];
export function getProject(slug:string) { return projects.find((project) => project.slug === slug); }
