const services = [
  { number: "01", name: "Film & Motion", copy: "Moving images with intention - from brand films to 3D visualisation.", tag: "FMD" },
  { number: "02", name: "Media Spaces", copy: "Light, space and digital layers for experiences that stay with you.", tag: "NMD" },
  { number: "03", name: "Wall Design", copy: "Walls as a shift in perspective - painted, spatial and unmistakable.", tag: "WALL" },
  { number: "04", name: "Logo Design", copy: "Identities with character. Made by designers, not generators.", tag: "ID" },
];

export default function EnglishHome() {
  return <main>
    <nav className="nav wrap"><a className="wordmark" href="/en">PARADOLOGIX<span>®</span></a><div className="navlinks"><a href="/en/work">Work</a><a href="#services">Services</a><a href="/en/studio">Studio</a></div><a className="nav-cta" href="/en/contact">Start a project <i>↗</i></a></nav>
    <section className="hero wrap" id="top"><div className="hero-copy"><p className="eyebrow"><span /> CREATIVE MEDIA STUDIO</p><h1>Make space<br />for the <em>impossible.</em></h1><p className="lede">We create visual worlds across film, space, walls and identity - for brands, places and ideas with depth.</p><a className="round-link" href="#work"><b>Explore our<br />perspectives</b><span>↓</span></a></div><div className="portal" aria-hidden="true"><div className="portal-glow" /><div className="portal-frame portal-frame-a" /><div className="portal-frame portal-frame-b" /><div className="portal-orb" /><div className="portal-label">ENTER<br />ANOTHER<br />DIMENSION</div></div><div className="hero-footer"><span>Scroll to explore</span><span className="line" /><span>01 — 04</span></div></section>
    <section className="statement wrap" id="studio"><p className="eyebrow">OUR POINT OF VIEW</p><h2>A world within space.<br /><em>A space through a world.</em></h2><p>Paradologix makes the invisible tangible. We bring precise planning and artistic intuition together - digital systems with material presence, clear communication with real impact.</p></section>
    <section className="work-section" id="work"><div className="wrap section-head"><p className="eyebrow">SELECTED WORK</p><a href="/en/work">View all projects <i>↗</i></a></div><div className="project-grid wrap"><article className="project violet"><div className="project-art"><div className="shape one" /><div className="shape two" /><div className="project-cross" /></div><p>SPATIAL / 01</p><h3>A room inside a room</h3><span>↗</span></article><article className="project moss"><div className="project-art"><div className="shape one" /><div className="shape two" /><div className="project-cross" /></div><p>WALL / 02</p><h3>The impossible garden</h3><span>↗</span></article><article className="project amber"><div className="project-art"><div className="shape one" /><div className="shape two" /><div className="project-cross" /></div><p>MOTION / 03</p><h3>Matter in motion</h3><span>↗</span></article></div></section>
    <section className="services wrap" id="services"><div className="section-head"><p className="eyebrow">WHAT WE MAKE</p><p>Four disciplines.<br />One perspective.</p></div><div className="service-list">{services.map((service, index) => { const slugs = ["explainer-video-agency", "digital-signage-content", "mural-artist", "logo-design-agency"]; return <a href={`/en/services/${slugs[index]}`} className="service" key={service.number}><span className="service-num">{service.number}</span><h3>{service.name}</h3><p>{service.copy}</p><span className="service-tag">{service.tag}</span><b>↗</b></a>; })}</div></section>
    <section className="contact wrap" id="contact"><p className="eyebrow">LET&apos;S BUILD A WORLD</p><h2>An idea?<br /><em>Open the portal.</em></h2><a href="/en/contact" className="email">Start a project <span>↗</span></a></section><footer className="footer wrap"><a className="wordmark" href="/en">PARADOLOGIX<span>®</span></a><p>© 2026 Paradologix</p><a href="/impressum">Imprint</a><a href="/">DE ↑</a></footer>
  </main>;
}
